language: python
python:
- 3.9
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  username: __token__
  password:
    secure: tg2j/eJrr6Heir1JTLVt9eXWqGDirrxbDQrnCXaKkALZMQjZd0Ft09tjqrjHBVH+47c9KfSjY9cOHCB6HKtkbjjicCu7N2B37qkb4/NDj3O+wPNdrLIvo9RzDRiHhweGRht2EXKDuUMBzIzspOBpzHKn19nm6pSxjKvjAZ4WEdquqAVR/hoVkDqJnIVyiB7CHq4KCVLLObs6iTM3cW9A2GSJHJKFlk3MYilPu2kb7ys7RylLUDfqWMbqbOqq/OvbpKp8axz7RDZlPVEOmotx+/KZTPki1qTVUCSIzjKoTKeRBMtSVlVLb9PY/iwXAFZP/MHwDbJ5yak5BhDo+zC4kDimmqOzrzgyJgC/8wNR5t/bqHj50GokKdt3bBxFURa7ULW7NymQHHqJBJvZKWP14BN8YVZJwqAmFeFrTsnt8vWG4YFSMjaxFz5hOxzvHtrFvt8atynDRr5xz1a7GZEeF80i8bd7gkTOR5m9Eb1Geg/IvLeDFZeeQHJWcalU0j1pFiXDWDdipY0DWUDAFYpQBIpY9PxIzuYEfM2Iqgp5TT8+BtgjmUFolL72VyuFWmiz3YBGTT/R2XguWXFfZm2DQwS/8enBoSijbs/YFQ6wQqp9AgSj1aymZCaG3rC7z9nkl9pCPJFHjCpE8MOEQbgtpqJNMQyExDZ84V1B8TXMhzA=
  on:
    tags: true
    repo: mCodingLLC/longest_increasing_subsequence
    python: 3.9
